apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: solaresporte.com.br
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: goserver-service
                port:
                  number: 80
            path: /admin
