apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: server
      containers:
        - name: server
          image: wesleywillians/hello-express
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: chave
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
        - name: chave
          secret:
            secretName: chave
